# Generated by Django 5.0.1 on 2025-08-06 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_facturacion', models.CharField(max_length=100)),
                ('apellido_facturacion', models.CharField(max_length=100)),
                ('email_facturacion', models.EmailField(max_length=254)),
                ('telefono_facturacion', models.CharField(max_length=20)),
                ('direccion_facturacion', models.CharField(max_length=200)),
                ('ciudad_facturacion', models.CharField(max_length=100)),
                ('codigo_postal_facturacion', models.CharField(max_length=10)),
                ('provincia_facturacion', models.CharField(max_length=100)),
                ('envio_diferente', models.BooleanField(default=False)),
                ('nombre_envio', models.CharField(blank=True, max_length=100)),
                ('apellido_envio', models.CharField(blank=True, max_length=100)),
                ('direccion_envio', models.CharField(blank=True, max_length=200)),
                ('ciudad_envio', models.CharField(blank=True, max_length=100)),
                ('codigo_postal_envio', models.CharField(blank=True, max_length=10)),
                ('provincia_envio', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('stripe', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('mercadopago', 'Mercado Pago')], max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas (no visibles para el cliente)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('codigo_producto', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que cambió el estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedidos',
                'ordering': ['-creado'],
            },
        ),
    ]
